package net.javacourse.entities;
// Generated 24 May 2021, 17:03:10 by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private Integer accId;
	private Students students;
	private String username;
	private String password;
	private byte level;
	private Date createdAt;
	private Date updatedAt;
	private Set previlegeses = new HashSet(0);

	public Accounts() {
	}

	public Accounts(Students students, String username, String password, byte level, Date createdAt, Date updatedAt) {
		this.students = students;
		this.username = username;
		this.password = password;
		this.level = level;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Accounts(Students students, String username, String password, byte level, Date createdAt, Date updatedAt,
			Set previlegeses) {
		this.students = students;
		this.username = username;
		this.password = password;
		this.level = level;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.previlegeses = previlegeses;
	}

	public Integer getAccId() {
		return this.accId;
	}

	public void setAccId(Integer accId) {
		this.accId = accId;
	}

	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getLevel() {
		return this.level;
	}

	public void setLevel(byte level) {
		this.level = level;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getPrevilegeses() {
		return this.previlegeses;
	}

	public void setPrevilegeses(Set previlegeses) {
		this.previlegeses = previlegeses;
	}

}
