package net.javacourse.entities;
// Generated 4 Jun 2021, 21:42:10 by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer classId;
	private String name;
	private int total;
	private int totalMales;
	private int totalFemales;
	private Set studentses = new HashSet(0);

	public Classes() {
	}

	public Classes(String name, int total, int totalMales, int totalFemales) {
		this.name = name;
		this.total = total;
		this.totalMales = totalMales;
		this.totalFemales = totalFemales;
	}

	public Classes(String name, int total, int totalMales, int totalFemales, Set studentses) {
		this.name = name;
		this.total = total;
		this.totalMales = totalMales;
		this.totalFemales = totalFemales;
		this.studentses = studentses;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public int getTotalMales() {
		return this.totalMales;
	}

	public void setTotalMales(int totalMales) {
		this.totalMales = totalMales;
	}

	public int getTotalFemales() {
		return this.totalFemales;
	}

	public void setTotalFemales(int totalFemales) {
		this.totalFemales = totalFemales;
	}

	public Set getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set studentses) {
		this.studentses = studentses;
	}

}
