package net.javacourse.entities;
// Generated 4 Jun 2021, 21:42:10 by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private String code;
	private Semesters semesters;
	private String name;
	private int credits;
	private int slots;
	private int year;
	private Set scheduleses = new HashSet(0);

	public Courses() {
	}

	public Courses(String code, String name, int credits, int slots, int year) {
		this.code = code;
		this.name = name;
		this.credits = credits;
		this.slots = slots;
		this.year = year;
	}

	public Courses(String code, Semesters semesters, String name, int credits, int slots, int year, Set scheduleses) {
		this.code = code;
		this.semesters = semesters;
		this.name = name;
		this.credits = credits;
		this.slots = slots;
		this.year = year;
		this.scheduleses = scheduleses;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Semesters getSemesters() {
		return this.semesters;
	}

	public void setSemesters(Semesters semesters) {
		this.semesters = semesters;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getCredits() {
		return this.credits;
	}

	public void setCredits(int credits) {
		this.credits = credits;
	}

	public int getSlots() {
		return this.slots;
	}

	public void setSlots(int slots) {
		this.slots = slots;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public Set getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(Set scheduleses) {
		this.scheduleses = scheduleses;
	}

}
