package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

/**
 * CurrentSem generated by hbm2java
 */
public class CurrentSem implements java.io.Serializable {

	private Integer id;
	private Semesters semesters;
	private int year;
	private String subName;

	public CurrentSem() {
	}

	public CurrentSem(Semesters semesters, int year, String subName) {
		this.semesters = semesters;
		this.year = year;
		this.subName = subName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Semesters getSemesters() {
		return this.semesters;
	}

	public void setSemesters(Semesters semesters) {
		this.semesters = semesters;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

}
