package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

/**
 * Previleges generated by hbm2java
 */
public class Previleges implements java.io.Serializable {

	private Integer id;
	private int accId;
	private String name;
	private byte add;
	private boolean delete;
	private boolean manage;

	public Previleges() {
	}

	public Previleges(int accId, String name, byte add, boolean delete, boolean manage) {
		this.accId = accId;
		this.name = name;
		this.add = add;
		this.delete = delete;
		this.manage = manage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAccId() {
		return this.accId;
	}

	public void setAccId(int accId) {
		this.accId = accId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getAdd() {
		return this.add;
	}

	public void setAdd(byte add) {
		this.add = add;
	}

	public boolean isDelete() {
		return this.delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}

	public boolean isManage() {
		return this.manage;
	}

	public void setManage(boolean manage) {
		this.manage = manage;
	}

}
