package net.javacourse.entities;
// Generated 24 May 2021, 17:03:10 by Hibernate Tools 5.4.30.Final

/**
 * Previleges generated by hbm2java
 */
public class Previleges implements java.io.Serializable {

	private Integer id;
	private Accounts accounts;
	private String name;
	private byte add;
	private boolean delete;
	private boolean manage;

	public Previleges() {
	}

	public Previleges(Accounts accounts, String name, byte add, boolean delete, boolean manage) {
		this.accounts = accounts;
		this.name = name;
		this.add = add;
		this.delete = delete;
		this.manage = manage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getAdd() {
		return this.add;
	}

	public void setAdd(byte add) {
		this.add = add;
	}

	public boolean isDelete() {
		return this.delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}

	public boolean isManage() {
		return this.manage;
	}

	public void setManage(boolean manage) {
		this.manage = manage;
	}

}
