package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

/**
 * Schedules generated by hbm2java
 */
public class Schedules implements java.io.Serializable {

	private Integer id;
	private Courses courses;
	private String day;
	private int shift;
	private String room;

	public Schedules() {
	}

	public Schedules(Courses courses, String day, int shift, String room) {
		this.courses = courses;
		this.day = day;
		this.shift = shift;
		this.room = room;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public int getShift() {
		return this.shift;
	}

	public void setShift(int shift) {
		this.shift = shift;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

}
