package net.javacourse.entities;
// Generated 12 Jun 2021, 09:55:29 by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Schedules generated by hbm2java
 */
public class Schedules implements java.io.Serializable {

	private Integer id;
	private Courses courses;
	private String day;
	private int shift;
	private String room;
	private String teacher;
	private Set studieses = new HashSet(0);

	public Schedules() {
	}

	public Schedules(Courses courses, String day, int shift, String room, String teacher) {
		this.courses = courses;
		this.day = day;
		this.shift = shift;
		this.room = room;
		this.teacher = teacher;
	}

	public Schedules(Courses courses, String day, int shift, String room, String teacher, Set studieses) {
		this.courses = courses;
		this.day = day;
		this.shift = shift;
		this.room = room;
		this.teacher = teacher;
		this.studieses = studieses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public int getShift() {
		return this.shift;
	}

	public void setShift(int shift) {
		this.shift = shift;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public Set getStudieses() {
		return this.studieses;
	}

	public void setStudieses(Set studieses) {
		this.studieses = studieses;
	}

}
