package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semesters generated by hbm2java
 */
public class Semesters implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer semId;
	private int year;
	private String subName;
	private Date startDay;
	private Date endDay;
	private Set<Semesters> currentSems = new HashSet<Semesters>(0);
	private Set<Semesters> studentses = new HashSet<Semesters>(0);
	private Set<Semesters> courseses = new HashSet<Semesters>(0);

	public Semesters() {
	}

	public Semesters(int year, String subName, Date startDay, Date endDay) {
		this.year = year;
		this.subName = subName;
		this.startDay = startDay;
		this.endDay = endDay;
	}

	public Semesters(int year, String subName, Date startDay, Date endDay, Set<Semesters> currentSems, Set<Semesters> studentses,
			Set<Semesters> courseses) {
		this.year = year;
		this.subName = subName;
		this.startDay = startDay;
		this.endDay = endDay;
		this.currentSems = currentSems;
		this.studentses = studentses;
		this.courseses = courseses;
	}

	public Integer getSemId() {
		return this.semId;
	}

	public void setSemId(Integer semId) {
		this.semId = semId;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	public Date getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Date startDay) {
		this.startDay = startDay;
	}

	public Date getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Date endDay) {
		this.endDay = endDay;
	}

	public Set<Semesters> getCurrentSems() {
		return this.currentSems;
	}

	public void setCurrentSems(Set<Semesters> currentSems) {
		this.currentSems = currentSems;
	}

	public Set<Semesters> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Semesters> studentses) {
		this.studentses = studentses;
	}

	public Set<Semesters> getCourseses() {
		return this.courseses;
	}

	public void setCourseses(Set<Semesters> courseses) {
		this.courseses = courseses;
	}

}
