package net.javacourse.entities;
// Generated 24 May 2021, 17:03:10 by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semesters generated by hbm2java
 */
public class Semesters implements java.io.Serializable {

	private Integer semId;
	private int year;
	private String subName;
	private Date startDay;
	private Date endDay;
	private Set studentses = new HashSet(0);
	private Set courseses = new HashSet(0);

	public Semesters() {
	}

	public Semesters(int year, String subName, Date startDay, Date endDay) {
		this.year = year;
		this.subName = subName;
		this.startDay = startDay;
		this.endDay = endDay;
	}

	public Semesters(int year, String subName, Date startDay, Date endDay, Set studentses, Set courseses) {
		this.year = year;
		this.subName = subName;
		this.startDay = startDay;
		this.endDay = endDay;
		this.studentses = studentses;
		this.courseses = courseses;
	}

	public Integer getSemId() {
		return this.semId;
	}

	public void setSemId(Integer semId) {
		this.semId = semId;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	public Date getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Date startDay) {
		this.startDay = startDay;
	}

	public Date getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Date endDay) {
		this.endDay = endDay;
	}

	public Set getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set studentses) {
		this.studentses = studentses;
	}

	public Set getCourseses() {
		return this.courseses;
	}

	public void setCourseses(Set courseses) {
		this.courseses = courseses;
	}

}
