package net.javacourse.entities;
// Generated 12 Jun 2021, 09:55:29 by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Sessions generated by hbm2java
 */
public class Sessions implements java.io.Serializable {

	private Integer id;
	private Semesters semesters;
	private Date startDay;
	private Date endDay;
	private int year;

	public Sessions() {
	}

	public Sessions(Date startDay, Date endDay, int year) {
		this.startDay = startDay;
		this.endDay = endDay;
		this.year = year;
	}

	public Sessions(Semesters semesters, Date startDay, Date endDay, int year) {
		this.semesters = semesters;
		this.startDay = startDay;
		this.endDay = endDay;
		this.year = year;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Semesters getSemesters() {
		return this.semesters;
	}

	public void setSemesters(Semesters semesters) {
		this.semesters = semesters;
	}

	public Date getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Date startDay) {
		this.startDay = startDay;
	}

	public Date getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Date endDay) {
		this.endDay = endDay;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

}
