package net.javacourse.entities;
// Generated 24 May 2021, 17:03:10 by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private String studentId;
	private Classes classes;
	private Semesters semesters;
	private String fullname;
	private String citizenId;
	private String email;
	private String address;
	private String telephone;
	private Set accountses = new HashSet(0);
	private Set studieses = new HashSet(0);

	public Students() {
	}

	public Students(String studentId, Classes classes, Semesters semesters, String fullname, String citizenId,
			String email, String address, String telephone) {
		this.studentId = studentId;
		this.classes = classes;
		this.semesters = semesters;
		this.fullname = fullname;
		this.citizenId = citizenId;
		this.email = email;
		this.address = address;
		this.telephone = telephone;
	}

	public Students(String studentId, Classes classes, Semesters semesters, String fullname, String citizenId,
			String email, String address, String telephone, Set accountses, Set studieses) {
		this.studentId = studentId;
		this.classes = classes;
		this.semesters = semesters;
		this.fullname = fullname;
		this.citizenId = citizenId;
		this.email = email;
		this.address = address;
		this.telephone = telephone;
		this.accountses = accountses;
		this.studieses = studieses;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Semesters getSemesters() {
		return this.semesters;
	}

	public void setSemesters(Semesters semesters) {
		this.semesters = semesters;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getCitizenId() {
		return this.citizenId;
	}

	public void setCitizenId(String citizenId) {
		this.citizenId = citizenId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Set getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set accountses) {
		this.accountses = accountses;
	}

	public Set getStudieses() {
		return this.studieses;
	}

	public void setStudieses(Set studieses) {
		this.studieses = studieses;
	}

}
