package net.javacourse.entities;
// Generated 4 Jun 2021, 21:42:10 by Hibernate Tools 5.4.30.Final

/**
 * Studies generated by hbm2java
 */
public class Studies implements java.io.Serializable {

	private Integer id;
	private Schedules schedules;
	private Students students;

	public Studies() {
	}

	public Studies(Schedules schedules, Students students) {
		this.schedules = schedules;
		this.students = students;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Schedules getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Schedules schedules) {
		this.schedules = schedules;
	}

	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

}
