package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

/**
 * Studies generated by hbm2java
 */
public class Studies implements java.io.Serializable {

	private Integer id;
	private Courses courses;
	private Students students;

	public Studies() {
	}

	public Studies(Courses courses, Students students) {
		this.courses = courses;
		this.students = students;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

}
