package net.javacourse.entities;
// Generated 28 May 2021, 22:09:13 by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Timetable generated by hbm2java
 */
public class Timetable implements java.io.Serializable {

	private Integer id;
	private Courses courses;
	private int time;
	private Date startDay;
	private Date endDay;

	public Timetable() {
	}

	public Timetable(Courses courses, int time, Date startDay, Date endDay) {
		this.courses = courses;
		this.time = time;
		this.startDay = startDay;
		this.endDay = endDay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public Date getStartDay() {
		return this.startDay;
	}

	public void setStartDay(Date startDay) {
		this.startDay = startDay;
	}

	public Date getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Date endDay) {
		this.endDay = endDay;
	}

}
